feat: Show past events
compsci-adl/website pull request #123
Opened 2024-03-18 07:52 UTC by phoenixpereira

### Description
Shows past events on the events page.

### Changes Made
- Sorts events into upcoming or past based on date and time.
- Conditionally renders past events title and events if there are past events.
- Adds a greyscale effect to past events to further differentiate them.

### Related Issues
Fixes #52.

### Additional Notes
N/A

2024-03-18 08:04 UTC, jsun969 requested changes

2024-03-18 08:04 UTC, jsun969 commented on src/app/events/Events.tsx
> +                    className={`w-full shrink-0 rounded-lg border-[3px] border-black bg-white object-contain md:w-[450px] ${isPastEvent ? 'grayscale' : ''}`}
use clsx

2024-03-18 08:04 UTC, jsun969 commented on src/app/events/Events.tsx
> +                            className={`h-fit rounded-md border-[3px] border-black px-4 py-2 ${['bg-orange', 'bg-yellow', 'bg-purple'][index % 3]} ${isPastEvent ? 'grayscale' : ''}`}
use clsx

2024-03-18 08:04 UTC, jsun969 commented on src/app/events/Events.tsx
> +        const eventDate = new Date(
add a util function like `getEventDate`

2024-03-18 08:04 UTC, jsun969 commented on src/app/events/Events.tsx
> +function Title({ title }: { title: string }) {
```suggestion
function Title({ children }: { children: string }) {
```

2024-04-03 00:57 UTC, rayokamoto requested changes

2024-04-03 00:57 UTC, rayokamoto commented on src/utils/get-events-date.ts
> +// Convert event date and return past events in reversed order
By "reversed order" do you mean the most recent event is at the top? If so, maybe make this clearer in the comment

2024-04-03 01:18 UTC, rayokamoto approved these changes

2024-04-03 02:58 UTC, jsun969 approved these changes

2024-04-03 08:55 UTC, merged