feat: Add tech stack tags to ProjectCard component
compsci-adl/website pull request #152
Opened 2024-07-08 16:43 UTC by lemonteaau

### Description
Add tech stack tags to ProjectCard component

### Changes Made
- Add Tag component
- Add techStack in projects.ts
- Add Tag component in ProjectCard.tsx

### Related Issues
Add feat according to #151 

### Additional Notes
-

2024-07-09 10:44 UTC, phoenixpereira requested changes

2024-07-09 10:44 UTC, phoenixpereira commented on src/components/Tag.tsx
There doesn't seem to be enough contrast between the text colour and the tag colour. See https://webaim.org/resources/contrastchecker/. Try making the text colour grey and making the darker tag colours a bit lighter.

2024-07-09 10:44 UTC, phoenixpereira commented on src/constants/colours.ts
> +    'Tailwind CSS': '#8876BE',
Make this colour a bit lighter, like #907FC3.

2024-07-09 10:44 UTC, phoenixpereira commented on src/constants/colours.ts
> +    'Discord.py': '#5E74C7',
Make this colour a bit lighter, like #7387CE.

2024-07-09 10:44 UTC, phoenixpereira commented on src/data/future-projects.ts
> +    {
Rename MyScheduler to MyTimetable. We decided MyTimetable sounds better than MyScheduler.

2024-07-09 10:44 UTC, phoenixpereira commented on src/data/future-projects.ts
> +    },
Remove Beautiful Soup from the tech stack. We recently discovered that the UofA courses website actually has an API which we can use, so we won't be using Beautiful Soup for this project.

2024-07-09 10:44 UTC, phoenixpereira commented on src/components/Tag.tsx
> +            className={`h-fit w-fit rounded-xl border border-slate-500 px-3 py-1.5 text-white`}
Use `border-black` instead of `border-slate-500` and use `border-2` instead of `border`.

2024-07-09 10:44 UTC, phoenixpereira commented on src/app/open-source/FutureProjectCard.tsx
> +                <div className="mt-4 space-y-2 md:space-y-4">
Remove `mt-4` since it gives the card an unneeded margin at the top.

2024-07-09 14:02 UTC, lemonteaau commented on src/components/Tag.tsx
Hi, I've tried the checker, but it seems very hard to pass the checker when choosing lighter background color and darker text at the same time. For example, #F7F7F7 for text and #64B550 for background. When the #64B550 turn lighter the contrast ratio decrease. 

<img width="609" alt="image" src="https://github.com/compsci-adl/website/assets/104964583/ac2eaa5b-6e59-4e1c-943e-2e4dd27f6ed1">
<img width="629" alt="image" src="https://github.com/compsci-adl/website/assets/104964583/f04ed73f-8bbb-4930-9044-2c566f3ddd38">

Maybe we can choose black for text, or use icons to replace text?

2024-07-09 16:35 UTC, rayokamoto requested changes
A few small changes + added to the discussion on colour contrast.

2024-07-09 16:35 UTC, rayokamoto commented on src/components/Tag.tsx
I suggest just creating a function to change the text to black or white depending on the background colour.

Here is a good [Stackoverflow post](https://stackoverflow.com/questions/1855884/determine-font-color-based-on-background-color) on the matter.

2024-07-09 16:35 UTC, rayokamoto commented on src/constants/colours.ts
> +    'Beautiful Soup': '#F69800',
Maybe remove this for now, since we aren't using Beautiful Soup

2024-07-09 16:35 UTC, rayokamoto commented on src/constants/colours.ts
> +    'Fast API': '#F6BF00',
```suggestion
    'FastAPI': '#F6BF00',
```

2024-07-09 16:35 UTC, rayokamoto commented on src/data/future-projects.ts
> +        techStack: ['Python', 'Fast API'],
```suggestion
        techStack: ['Python', 'FastAPI'],
```

2024-07-10 00:47 UTC, phoenixpereira commented on src/components/Tag.tsx
Yeah I agree with Ray, making a function to do this should fix the contrast issue.

2024-07-10 04:02 UTC, phoenixpereira requested changes

2024-07-10 04:02 UTC, phoenixpereira commented on src/constants/colours.ts
> +    'FastAPI': '#F6BF00',
Replace `'FastAPI': '#F6BF00','` with `FastAPI: '#F6BF00',` to fix the prettier error.

2024-07-10 05:13 UTC, lemonteaau reviewed
All done

2024-07-10 07:34 UTC, rayokamoto requested changes

2024-07-10 07:34 UTC, rayokamoto commented on src/constants/colours.ts
> +
```suggestion
```

2024-07-10 07:34 UTC, rayokamoto commented on src/constants/colours.ts
> + * 3.0.
I think just having the link to the source is sufficient attribution, according to this: https://stackoverflow.blog/2009/06/25/attribution-required/

I'd probably note that it takes in a string that represents a hex color as well

2024-07-10 07:55 UTC, jsun969 requested changes
All good, just a few suggestions

2024-07-10 07:55 UTC, jsun969 commented on src/constants/colours.ts
> +export const getContrastColor = function (backgroundColor: string) {
```suggestion
export const getContrastColor = (backgroundColor: string) => {
```

2024-07-10 07:55 UTC, jsun969 commented on src/data/projects.ts
Cound you add a constant variable for tech stacks for type safe? like

```ts
const TECH_STACK = ['Python', 'FastAPI', 'TypeScript', ...] as const;
export type TechStack = (typeof TECH_STACK)[number];
//           ^ 'Python' | 'FastApi' | 'Typescript' | ...
```

Then use this `TechStack` type for interfaces and colours

2024-07-10 07:55 UTC, jsun969 commented on src/app/open-source/FutureProjectCard.tsx
> +                    {project.techStack && (
```suggestion
                    {project.techStack.length !== 0 && (
```

2024-07-10 10:54 UTC, jsun969 approved these changes
LGTM

2024-07-10 11:03 UTC, phoenixpereira approved these changes
LGTM

2024-07-10 11:05 UTC, rayokamoto approved these changes

2024-07-10 11:10 UTC, merged