fix: existing email error popup
compsci-adl/website pull request #160
Opened 2024-07-27 17:00 UTC by Techngo10

Description
Added Error message for existing email used

Changes Made
Added line 133 - 136

Related Issues
[Bug] Signing up with an account that already exists doesn’t show the error in the UI. Fixes #149 

Additional Info
Changed step one line 135, as it had unnecessary white space, and it wasn't pretty enough

2024-07-28 02:38 UTC, phoenixpereira commented
@Techngo10 To test it, you would need to make a Clerk account and make an account with an email address and then try making a new account with the same email address. See https://github.com/compsci-adl/website/blob/main/docs/clerk.md.

2024-07-28 02:43 UTC, phoenixpereira requested changes

2024-07-28 02:43 UTC, phoenixpereira commented on src/app/(account)/join/steps/StepOne.tsx
> +                    code: 'form_email_already_exists',
Code should be `form_identifier_exists`.

2024-07-29 01:48 UTC, rayokamoto approved these changes

2024-07-29 04:44 UTC, phoenixpereira approved these changes

2024-07-29 04:45 UTC, merged