Update Tech Stack on open source page
compsci-adl/website pull request #170
Opened 2024-08-04 15:56 UTC by KnightRadiant44

### Description
Update few tech stacks on open source page

### Changes Made
Added the necessary tech stack requested.

### Related Issues
Fixes #169 

### Additional Notes
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/729a4720-1ad5-44c1-9713-6555ec704960">

2024-08-04 16:00 UTC, KnightRadiant44 commented
It worked!! Apologies for the mistakes earlier, I didn't mean to do that. This was a really good learning experience for me :))

2024-08-04 17:03 UTC, rayokamoto requested changes

2024-08-04 17:03 UTC, rayokamoto commented on dump.rdb
This file shouldn't be here. Remember not to `git add .` without first checking what files were changed (e.g. with `git status`). Check what files are being added before you stage your changes and commit.

2024-08-04 17:03 UTC, rayokamoto commented on src/constants/colours.ts
> +    NextUI: '#A8DADC',
Could you order this alphabetically within the `TECH_COLORS` list?

2024-08-04 17:03 UTC, rayokamoto commented on src/constants/tech-stack.ts
> +    'NextUI',
Could you order this alphabetically? I know the current list isn't either but it'll be nicer if the entire list was ordered.

2024-08-05 01:06 UTC, phoenixpereira requested changes

2024-08-05 01:06 UTC, phoenixpereira commented on src/constants/colours.ts
> +    Requests: '#FFD166',
This colour is to similar to the colour used for FastAPI, can you please change the colour. The dark blue colour you used previously would be fine.

2024-08-05 01:06 UTC, phoenixpereira commented on src/constants/colours.ts
> +    Vite: '#646464',
Can you change this to a colour beside grey, perhaps light blue or orange.

2024-08-05 01:35 UTC, phoenixpereira approved these changes

2024-08-05 01:41 UTC, rayokamoto requested changes

2024-08-05 01:41 UTC, rayokamoto commented on .gitignore
> +*.sqlite
```suggestion
*.sqlite

```

2024-08-05 02:04 UTC, rayokamoto approved these changes

2024-08-05 02:37 UTC, merged