feat: Add Upcoming events
compsci-adl/website pull request #182
Opened 2024-08-25 05:41 UTC by codingzilin

### Description
Added upcoming events for home page.

### Changes Made

- Upcoming events card.
- Added conditional rendering for the 'Upcoming Events' section.
- Included a map function to iterate over UPCOMING_EVENTS and render UpcomingEventCard components."

### Related Issues
#166 

### Additional Notes
N/A

2024-08-25 06:38 UTC, phoenixpereira requested changes

2024-08-25 06:38 UTC, phoenixpereira commented on package.json
Please keep the package version the same to ensure consistency.

2024-08-25 06:38 UTC, phoenixpereira commented on src/app/(home)/page.tsx
> +}
Make this a seperate component by moving it to a new file within the `(home)` folder.

2024-08-25 06:38 UTC, phoenixpereira commented on src/app/(home)/page.tsx
> +                            </div>
Make "New Members are" and "Always Welcome" go on seperate lines like this:

<img width="191" alt="image" src="https://github.com/user-attachments/assets/4cfbf49f-d70a-4a36-84e4-3e80b86a4b72">

2024-08-25 06:38 UTC, phoenixpereira commented on src/app/(home)/page.tsx
> +                            </div>
Make the event time and location text smaller and not bold by adding `text-lg font-normal` to the `className`. Doing this should help fix the icons being different sizes.

2024-08-25 06:38 UTC, phoenixpereira commented on src/app/(home)/page.tsx
> +                        </div>
Fix the icons being different sizes. This is caused by the event location being two lines while event time is only one.
<img width="582" alt="image" src="https://github.com/user-attachments/assets/8432009e-9467-4c93-b091-1f077c36d2a4">

2024-08-25 06:38 UTC, phoenixpereira commented on src/app/(home)/page.tsx
> +                        <div className="relative z-10 mt-12 text-2xl font-black md:flex-row lg:ml-4 lg:mt-24 lg:text-3xl">
Add a bit more horizontal gap between this and the New Members are Always Welcome section by changing `lg:ml-4` to `lg:ml-10`

2024-08-25 06:38 UTC, phoenixpereira commented on src/app/(home)/page.tsx
> +                            <div className="flex justify-end">
The title shouldn't be justified to the end on mobile.

2024-08-26 05:39 UTC, codingzilin commented
Fixed changes required

2024-08-26 08:02 UTC, phoenixpereira requested changes
Just some small changes needed.

2024-08-27 04:36 UTC, codingzilin commented
Thx Phoenix, fixed changes required.

2024-08-27 05:43 UTC, phoenixpereira approved these changes

2024-08-29 23:07 UTC, rayokamoto approved these changes

2024-08-30 00:58 UTC, merged