Feat/committee names
compsci-adl/website pull request #209
Opened 2024-11-22 06:14 UTC by shxhid01

### Description
Updated committee names for club page as handover had happened

### Changes Made
Changed names and added correct roles to them

### Related Issues
N/A

### Additional Notes
I've ordered it so it goes from exec committee then manager to officers for all the roles

2024-11-22 11:33 UTC, jsun969 requested changes

2024-11-22 11:33 UTC, jsun969 commented on src/data/committee-members.ts
> +        name: 'Matilda Cotton ',
```suggestion
        name: 'Matilda Cotton',
```

2024-11-22 11:33 UTC, jsun969 commented on src/data/committee-members.ts
> +        name: 'Shahid Hussain  ',
```suggestion
        name: 'Shahid Hussain',
```

2024-11-22 11:40 UTC, jsun969 requested changes

2024-11-22 11:40 UTC, jsun969 commented on package.json
I don't think `package.json` should be updated. Also we're using pnpm so install with `pnpm install` instead of `npm install` so there shouldn't be `package-lock.json` either.

2024-11-22 11:40 UTC, jsun969 commented on package-lock.json
remove this file

2024-11-22 11:47 UTC, jsun969 approved these changes
LGTM

2024-11-24 12:22 UTC, shxhid01 reviewed
LGTM

2024-11-25 09:48 UTC, jsun969 requested changes

2024-11-25 09:48 UTC, jsun969 commented on src/data/committee-members.ts
> +        name: 'LLoyd Draysey',
```suggestion
        name: 'Lloyd',
```

2024-11-25 09:53 UTC, phoenixpereira requested changes

2024-11-25 09:53 UTC, phoenixpereira commented on src/data/committee-members.ts
> +        position: 'Events Officer',
```suggestion
        name: 'Lloyd',
        position: 'Events Officer',
```

2024-11-25 10:14 UTC, jsun969 approved these changes

2024-11-25 10:16 UTC, phoenixpereira approved these changes

2024-11-25 10:32 UTC, merged