Feat/improve open source page
compsci-adl/website pull request #210
Opened 2024-11-23 06:09 UTC by codingzilin

### Description
*Improve open source page.*

### Changes Made
*Added title section, introduction section, photo and replaced button with hyperlink.*

### Related Issues
*Feature request #165 *

### Additional Notes
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/a6aef285-f5db-48b5-b415-da1ea262f021">

2024-11-23 06:34 UTC, jsun969 requested changes

2024-11-23 06:34 UTC, jsun969 commented on src/app/open-source/page.tsx
> +                                        }
```suggestion
                                        href="https://docs.google.com/forms/d/e/1FAIpQLSe2uvnn4qW95yJ7TzyDo7QMjzhkawvdERRDmeBLMwloi-nqjg/viewform"
```

2024-11-23 06:34 UTC, jsun969 commented on src/app/open-source/page.tsx
> +                                        className=" mr-4"
```suggestion
                                        className="mr-4"
```

2024-11-23 06:34 UTC, jsun969 commented on src/app/open-source/page.tsx
> +                                        alt={'Open source'}
```suggestion
                                        src="/images/opensource/csclub_open_source-2.png"
                                        alt="Open source"
```

2024-11-23 06:43 UTC, phoenixpereira requested changes

2024-11-23 06:43 UTC, phoenixpereira commented on public/images/opensource/csclub_open_source-2.png
Change the file name to just `opensource.png`

2024-11-23 06:43 UTC, phoenixpereira commented on src/app/open-source/page.tsx
> +                                            </span>
Make this bold.

2024-11-26 03:15 UTC, jsun969 requested changes

2024-11-26 03:15 UTC, jsun969 commented on src/app/open-source/page.tsx
> +                                            <span className="relative z-[2]  whitespace-nowrap border-2 border-white py-6 pl-4 pr-16 text-2xl font-bold underline lg:pr-36 lg:text-3xl">
```suggestion
                                            <span className="relative z-[2] whitespace-nowrap border-2 border-white py-6 pl-4 pr-16 text-2xl font-bold underline lg:pr-36 lg:text-3xl">
```

2024-11-26 03:27 UTC, jsun969 approved these changes

2024-11-26 07:32 UTC, phoenixpereira commented on src/app/open-source/page.tsx
> +                        <div className="grid grid-cols-1 gap-8 lg:grid-cols-2">
Fix the overlap at about 3/4 screen width by making the image go below the "Join the Open Source Team!" earlier (between `xl` and `2xl`). 

![image](https://github.com/user-attachments/assets/17f824a0-19ed-449b-a1ae-9fbfa0c877ed)

2024-11-26 07:35 UTC, phoenixpereira commented on src/app/open-source/page.tsx
> +                                    </Link>
Make the text a bit bigger for `sm`-`md` widths.

```suggestion
                                    <Link
                                        className="text-lg font-bold underline sm:text-2xl md:text-3xl"
                                        href="https://docs.google.com/forms/d/e/1FAIpQLSe2uvnn4qW95yJ7TzyDo7QMjzhkawvdERRDmeBLMwloi-nqjg/viewform"
                                    >
                                        Join the Open Source Team!
                                    </Link>
```

2024-11-26 07:39 UTC, phoenixpereira commented on src/app/open-source/page.tsx
Can you also update the text at the bottom to match this? 
Austin's GitHub profile link is: https://github.com/AustinH-adl

![image](https://github.com/user-attachments/assets/bc25afec-3dc0-4c9b-bb13-fa56949d24f3)

2024-11-27 07:54 UTC, phoenixpereira approved these changes

2024-11-27 07:55 UTC, merged