Add contacts page
compsci-adl/website pull request #30
Opened 2024-01-19 09:04 UTC by jsun969

close #22

2024-01-19 17:03 UTC, jsun969 commented
https://github.com/compsci-adl/website/blob/e15f232237824171beed0bca24b5ba99027e6d2a/src/app/contact/Form.tsx#L9-L12

Need backend here.

2024-01-20 02:51 UTC, rayokamoto requested changes

2024-01-20 02:51 UTC, rayokamoto commented on src/app/contact/Contact.tsx
> +import Paragraph from '../../components/Paragraph';
Change this to `@/components/Paragraph`

2024-01-20 02:51 UTC, rayokamoto commented on src/app/contact/Sponsorship.tsx
> +import Paragraph from '../../components/Paragraph';
change to `@/components/Paragraph`

2024-01-20 02:51 UTC, rayokamoto commented on src/app/contact/page.tsx
> +import Title from '../../components/Title';
Use `@/components/Title`

2024-01-20 02:53 UTC, rayokamoto commented
I wouldn't say this PR fully resolves #22 so although we can merge this, #22 should still be marked as "in progress" as the backend and the email integration does not yet exist.

2024-01-20 02:56 UTC, phoenixpereira approved these changes

2024-01-20 02:56 UTC, rayokamoto approved these changes
Good to go now

2024-01-20 02:57 UTC, merged